import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { getProjectRoot } from '../../bootstrap/state.js'
import {
  getProjectWorkflowsDir,
  getUserWorkflowsDir,
} from '../../tools/WorkflowTool/savedWorkflows.js'
import { validateWorkflowAssetSource } from '../../tools/WorkflowTool/workflowAsset.js'
import { deriveWorkflowSaveName } from './saveWorkflow.js'

export type WorkflowCreateArgs = {
  force: boolean
  user: boolean
  name?: string
  error?: string
}

export type WorkflowCreateResult = {
  ok: boolean
  message: string
  name?: string
  path?: string
  scope?: 'project' | 'user'
}

export const WORKFLOW_CREATE_USAGE =
  'Usage: /workflows create <name> [--user] [--force]'

export function parseWorkflowCreateArgs(
  args: readonly string[],
): WorkflowCreateArgs {
  const parsed: WorkflowCreateArgs = {
    force: false,
    user: false,
  }
  const positional: string[] = []
  for (const arg of args) {
    if (arg === '--force') {
      parsed.force = true
      continue
    }
    if (arg === '--user') {
      parsed.user = true
      continue
    }
    if (arg === '--help' || arg === '-h') {
      parsed.error = WORKFLOW_CREATE_USAGE
      continue
    }
    if (arg.startsWith('--')) {
      parsed.error = `Unknown workflow create option: ${arg}\n${WORKFLOW_CREATE_USAGE}`
      continue
    }
    positional.push(arg)
  }
  if (positional.length === 0) {
    return {
      ...parsed,
      error: WORKFLOW_CREATE_USAGE,
    }
  }
  const name = deriveWorkflowSaveName({ runId: positional.join('-') })
  if (!name) {
    return {
      ...parsed,
      error: 'Workflow name must include at least one letter, number, underscore, or dash.',
    }
  }
  return { ...parsed, name }
}

function jsString(value: string): string {
  return JSON.stringify(value)
}

export function buildWorkflowTemplate(name: string): string {
  const command = `/${name}`
  return `export const meta = {
  name: ${jsString(name)},
  description: ${jsString(`Reusable workflow template for ${name}.`)},
  whenToUse: ${jsString('Use after replacing the placeholder prompts with a bounded procedure for this workflow.')},
  argsSchema: {
    type: 'object',
    properties: {
      task: {
        type: 'string',
        description: 'Task, ticket, or question this workflow should complete.',
      },
    },
    required: ['task'],
    additionalProperties: true,
  },
  budgets: {
    timeoutMs: 600000,
    phaseTimeoutMs: 120000,
    maxAgents: 3,
    maxParallel: 2,
    maxNestedWorkflows: 0,
  },
  allowedTools: ['Read', 'Grep', 'Glob'],
  allowedRoots: ['.'],
  allowedHosts: [],
  effort: 'medium',
  evidence: {
    finalReport: true,
    citations: false,
    realProvider: false,
    processClean: true,
    validationCommands: [
      ${jsString(`mossen -p --output-format stream-json "${command} task=..."`)},
      ${jsString(`mossen -p --output-format stream-json "/workflows validate ${name} --strict"`)},
    ],
    artifacts: ['final-report.json', 'assertions.json'],
  },
  lifecycle: {
    version: '0.1.0',
    owner: 'project',
    status: 'draft',
    compatibility: 'Generated by /workflows create. Replace placeholder prompts before promotion.',
  },
  phases: [
    { title: 'Plan', detail: 'Clarify the input and split the work.' },
    { title: 'Execute', detail: 'Run bounded agent work.' },
    { title: 'Verify', detail: 'Check the result against acceptance criteria.' },
  ],
}

const input =
  args && typeof args === 'object' && !Array.isArray(args)
    ? args
    : { task: String(args ?? '') }
const task =
  typeof input.task === 'string' && input.task.trim()
    ? input.task.trim()
    : 'Replace this task with the workflow input.'
const evaluationPrompt =
  'Pass when the workflow returns a concise result, a verification review, and the evidence needed to rerun validation.'

phase('Plan')
log('Task:', task)
const plan = await agent(
  'Create a short execution plan for this workflow task. Keep it bounded and testable. Task: ' +
    task,
  { label: 'planner', phase: 'Plan' },
)

phase('Execute')
const result = await agent(
  'Execute the workflow task using the plan. Return only the useful result. Plan: ' +
    plan +
    '\\nTask: ' +
    task,
  { label: 'worker', phase: 'Execute' },
)

phase('Verify')
const review = await agent(
  'Review the workflow result for missing evidence, unchecked assumptions, and next validation steps. Result: ' +
    result,
  { label: 'verifier', phase: 'Verify' },
)

return {
  status: 'workflow-template-completed',
  task,
  result,
  review,
  evaluationPrompt,
}
`
}

export function createWorkflowCommand(
  args: readonly string[],
): WorkflowCreateResult {
  const parsed = parseWorkflowCreateArgs(args)
  if (parsed.error || !parsed.name) {
    return {
      ok: false,
      message: parsed.error ?? WORKFLOW_CREATE_USAGE,
    }
  }
  const scope = parsed.user ? 'user' : 'project'
  const dir = parsed.user
    ? getUserWorkflowsDir()
    : getProjectWorkflowsDir(getProjectRoot())
  const path = join(dir, `${parsed.name}.js`)
  if (existsSync(path) && !parsed.force) {
    return {
      ok: false,
      name: parsed.name,
      path,
      scope,
      message: `Workflow "${parsed.name}" already exists at ${path}. Use --force to overwrite it.`,
    }
  }
  const source = buildWorkflowTemplate(parsed.name)
  const validation = validateWorkflowAssetSource(source, {
    scope,
    scriptPath: path,
    requireBoundedBudgets: true,
    requirePhases: true,
  })
  if (!validation.ok) {
    return {
      ok: false,
      name: parsed.name,
      path,
      scope,
      message: `Generated workflow template failed validation: ${validation.issues
        .map(issue => `${issue.code}: ${issue.message}`)
        .join('; ')}`,
    }
  }
  try {
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    writeFileSync(path, source, 'utf8')
  } catch (err) {
    return {
      ok: false,
      name: parsed.name,
      path,
      scope,
      message: `Could not create workflow "${parsed.name}": ${
        err instanceof Error ? err.message : String(err)
      }`,
    }
  }
  return {
    ok: true,
    name: parsed.name,
    path,
    scope,
    message:
      `Created workflow "${parsed.name}" (${scope} scope) -> ${path}.` +
      `\nRun it with /${parsed.name} task=...` +
      `\nValidate it with /workflows validate ${parsed.name} --strict.`,
  }
}
